# -*- coding: utf-8 -*-
"""TASK_3 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7dk7aS0xX6rp8OMoxw_5fRf0KL7w1yK

**Task 3:** Creating a console application
for basic CRUD operations on a list
of tasks.

**Objective :** Implement Create, Read, Update, and Delete operations using lists for datastorage.
"""

class TaskManager :
  """
    A class representing a task in the task list.

    Attributes:
        task_id (int): A unique identifier for the task.
        title (str): The title of the task.
        description (str): A description of the task.
    """
  def __init__(self):
    self.tasks = []
    self.next_id = 1


  def create_task(self,title,description):
    task = {
        'task_id' : self.next_id,
        'title' : title,
        'description' : description
    }
    self.tasks.append(task)
    print(f"Task '{title}' created successfully with task ID {self.next_id} .")
    self.next_id += 1


  def read_tasks(self):
    if not self.tasks :
      print("No tasks available .")
    else:
      print("LIST OF TASKS : \n")
      for task in self.tasks :
        print(f"TASK ID : {task['task_id']}, TITLE : {task['title']}, DESCRIPTION : {task['description']}")
        print()


  def update_tasks(self, task_id, new_title = None, new_description = None):
    for task in self.tasks:
      if task['task_id'] == task_id :
        if new_title :
          task['title'] = new_title
        if new_description :
          task['description'] = new_description
        print(f"Task ID {task_id} updated successfully .")
        return

    print(f"Sorry ! Task with ID {task_id} not found . ")


  def delete_tasks(self, task_id):
    for task in self.tasks :
      if task['task_id'] == task_id :
        self.tasks.remove(task)
        print(f"Task with ID {task_id} deleted successfully . ")
        return

    print(f"Task with ID {task_id} not found . ")


def main():
  task_manager = TaskManager()


  while True:
    print("Task Manager : ")
    print("1. Create Task ")
    print("2. Read Tasks ")
    print("3. Update Tasks ")
    print("4. Delete Tasks ")
    print("5. Exit ")
    choice = input("Enter an option (1 - 5) : ")

    if choice == "1":
      title = input("Enter task title : ")
      description = input("Enter task description : ")
      task_manager.create_task(title, description)

    elif choice == "2":
      task_manager.read_tasks()

    elif choice == "3":
      task_id = int(input("Enter the task ID to update : "))
      new_title = input("Enter a new title for the task (Leave blank to keep the current title) : ")
      new_description = input("Enter a new description for the task (Leave blank to keep the current description) : ")
      task_manager.update_tasks(task_id, new_title if new_title else None, new_description if new_description else  None)

    elif choice == "4":
      task_id = int(input("Enter the task ID to delete : "))
      task_manager.delete_tasks(task_id)

    elif choice == "5":
      print("Exiting the Task Manger... Thank you !")
      break

    else :
      print("Invalid input ! Please try again . ")


if __name__ == "__main__" :
  main()