# -*- coding: utf-8 -*-
"""TASK 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAql_Mk6JaBR_4nvD2rTN0uLk5bTn0Uh

**Task 2:** Generate and print
simple number patterns.

**Objective:** Utilize loops to control the
structure of number patterns.
"""

def pyramid_pattern(n):

 """
    Prints a pyramid number pattern with 'n' rows based on user input.

    The pyramid consists of increasing numbers, starting from 1 at the top.
    Each row contains numbers starting from 1 and increasing up to the current row number,
    while the leading spaces decrease as the rows progress.

    Parameters:
    n (int): The number of rows in the pyramid, entered by the user.

    Example:
        For n = 4, the output will be:
            1
           1 2
          1 2 3
         1 2 3 4
    """

 for i in range (1 , n+1):
      for j in range (n-i):
        print(" " , end = "")
      for k in range (1 , i+1):
        print(k , end = " ")

      print()

n = int(input("Enter a number !"))
pyramid_pattern(n)