# -*- coding: utf-8 -*-
"""TASK 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pq5tAmrATyM5Xu4u35z9ZDCHzpy-rcSQ

**Task 1**: A basic text-based game.

**Objective:** Implement a simple game using conditional statements for game logic.
"""

import random

def number_guessing_game():

  """
    A simple number guessing game where the player has 5 attempts to guess a randomly
    generated number between 1 and 100.

    The game provides feedback after each guess, indicating whether the guess was too
    high or too low. The player is notified of the number of remaining attempts. If
    the correct number is guessed, a congratulatory message is displayed. If the player
    runs out of attempts without guessing the correct number, the correct number is revealed.

    No parameters are needed for this function.
    """

  print("WELCOME TO THE NUMBER GUESSING GAME !\n")

  number_to_guess = random.randint(1 , 100)

  no_of_tries = 5

  while no_of_tries > 0:

    if no_of_tries == 1:
      print("Last attempt !")
    else :
      print(f"You have {no_of_tries} attempts remaining !")

    guess = int(input("GUESS A NUMBER (Between 1 to 100) :"))

    if guess == number_to_guess:
      print("Confratulations ! You guessed it right .")
    elif no_of_tries > 1 :
      if guess > number_to_guess :
        print("Too high ! Try again .")
      else:
        print("Too low ! Try again .")

    no_of_tries -= 1

    if no_of_tries == 0:
      print(f"Oops! You lost. The correct number was {number_to_guess}")

number_guessing_game()