# -*- coding: utf-8 -*-
"""TASK 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3HAD9VIoNi62hGADlFWLbfUQ4fZ6San

**Task 4:** Building a temperature
converter program.

**Objective:** Enable users to input temperatures
and choose the conversion direction between
Fahrenheit and Celsius.
"""

def celsius_to_fahrenheit(celsius):
  return (celsius * 9/5) + 32

def fahrenheit_to_celsius(fahrenheit):
  return (fahrenheit - 32) * 5/9

def temperature_converter():
  """
    Interactive temperature converter between Celsius and Fahrenheit.

    This function provides a simple console-based interface for converting
    temperatures between Celsius and Fahrenheit based on user input. The user
    selects the conversion direction and provides the temperature to be converted.

    The function also handles invalid input, prompting the user for correct input.

    Usage:
        1. Celsius to Fahrenheit
        2. Fahrenheit to Celsius

    Raises:
        ValueError: If the user inputs an invalid number.
    """
  print("WELCOME TO THE TEMPERATURE CONVERTER !")
  print("1. Celsius to fahrenheit : ")
  print("2. Fahrenheit to celsius : ")

  try:
    option = int(input("Choose the conversion direction (1 or 2) : "))
    if option == 1:
      celsius = float(input("Enter temperature in celsius : "))
      fahrenheit = celsius_to_fahrenheit(celsius)
      print(f"{celsius}°C is {fahrenheit:.2f}°F .")

    elif option == 2:
      fahrenheit = float(input("Enter temperature in fahrenheit : "))
      celsius = fahrenheit_to_celsius(fahrenheit)
      print(f"{fahrenheit}°F is {celsius:.2f}°C .")

    else:
      print("Invalid option ! Please enter 1 or 2.")

  except ValueError :
    print("Please enter a valid number .")

temperature_converter()